# Generated by Django 5.1.2 on 2024-12-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.TextField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Company', models.CharField(blank=True, max_length=255, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('JobDescription', models.TextField(blank=True, null=True)),
                ('JobRequirements', models.TextField(blank=True, null=True)),
                ('RequiredQual', models.TextField(blank=True, null=True)),
                ('Salary', models.CharField(blank=True, max_length=50, null=True)),
                ('AboutC', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
