# Generated by Django 5.1.2 on 2024-12-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_joblisting_delete_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='JobRequirements',
            new_name='JobRequirement',
        ),
    ]
