# Generated by Django 5.1.2 on 2024-12-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_jobrequirements_joblisting_jobrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='StartDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
